apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: helloworld-deployment
  template:
    metadata:
      labels:
        app: helloworld-dep
        name: helloworld-deployment
    spec:
      containers:
      - name: nodejs-demo
        image: varunbhatbm/nodejs-docker-demo
        ports:
        - containerPort: 3000 
          name: nodejs-port
        volumeMounts:
        - mountPath: /myvol
          name: myvolume
      volumes:
      - name: myvolume
        awsElasticBlockStore:
          volumeID: vol-01d0a06be25e679d4