apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 4
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      name: helloworld-deployment
  template:
    metadata:
      labels:
        app: helloworld-dep
        name: helloworld-deployment
    spec:
      containers:
      - name: nodejs-demo
        image: varunbhatbm/nodejs-docker-demo
        ports:
        - containerPort: 3000 
          name: nodejs-port
        volumeMounts:
        - name: cred-volume
          mountPath: /etc/creds
          readOnly: true
      volumes:
      - name: cred-volume
        secret:
          secretName: db-secret

        