apiVersion: v1
kind: Pod
metadata:
  name: helloworld-nginx
  labels:
    app: helloworld-nginx-app
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - name: nginx-port
      containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /etc/nginx/conf.d
  - name: helloworld-demo
    image: varunbhatbm/nodejs-docker-demo:2
    ports:
    - containerPort: 3000
  volumes:
  - name: config-volume
    configMap:
      name: nginx-config
      items:
      - key: reverseproxy.conf
        path: reverseproxy.conf

