apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  ports:
  - port: 31001
    nodePort: 31001
    protocol: TCP
  selector:
    app: wordpress-dep
    # name: wordpress-dep
  type: NodePort